import type { MLSListing, PropertyDisplayData, PropertyFilters } from './types';
import { isListingDisplayable } from './compliance';

// Mock MLS data following RESO/Spark API standard
// TODO: Replace with real Spark API integration when GEPAR credentials are available

export const MOCK_MLS_LISTINGS: MLSListing[] = [
  {
    ListingId: 'EP2026-4521',
    ListingKey: 'EP2026-4521-KEY',
    ModificationTimestamp: '2026-02-10T10:30:00Z',
    ListOfficeName: 'The Right Move Real Estate Group',
    ListOfficeKey: 'RIGHTMOVE001',
    ListAgentFullName: 'Lorena Ontiveros-Ortega',
    ListAgentKey: 'LO001',
    ListAgentMLSID: 'EP-LO-2024',
    StandardStatus: 'Active',
    ListPrice: 359000,
    OriginalListPrice: 365000,
    UnparsedAddress: '4521 Loma de Plata Dr',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79934',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    BathroomsFull: 2,
    BathroomsHalf: 1,
    LivingArea: 2450,
    LotSizeAcres: 0.25,
    YearBuilt: 2019,
    Media: [
      { MediaURL: '/images/properties/home-1.jpg', Order: 1 },
    ],
    Latitude: 31.8418,
    Longitude: -106.5628,
    PublicRemarks: 'Stunning modern home in prestigious Westside location. Open floor plan with gourmet kitchen, quartz countertops, and stainless steel appliances. Master suite with spa-like bathroom. Low-maintenance desert landscaping.',
    DaysOnMarket: 12,
    VirtualTourURLUnbranded: undefined,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Disposal', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Attached'],
    SubdivisionName: 'Loma de Plata',
    MLSAreaMajor: 'Westside',
  },
  {
    ListingId: 'EP2026-8765',
    ListingKey: 'EP2026-8765-KEY',
    ModificationTimestamp: '2026-02-09T14:15:00Z',
    ListOfficeName: 'The Right Move Real Estate Group',
    ListOfficeKey: 'RIGHTMOVE001',
    ListAgentFullName: 'Lorena Ontiveros-Ortega',
    ListAgentKey: 'LO001',
    ListAgentMLSID: 'EP-LO-2024',
    StandardStatus: 'Active',
    ListPrice: 425000,
    UnparsedAddress: '8765 Rio Grande Blvd',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79932',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 2100,
    LotSizeAcres: 0.5,
    YearBuilt: 2015,
    Media: [
      { MediaURL: '/images/properties/home-2.jpg', Order: 1 },
    ],
    Latitude: 31.8762,
    Longitude: -106.5821,
    PublicRemarks: 'Peaceful retreat near the Rio Grande. Lush landscaping, spacious lot, updated throughout with modern finishes. Perfect for families seeking tranquility in the Upper Valley.',
    DaysOnMarket: 8,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage'],
    SubdivisionName: 'Upper Valley Estates',
    MLSAreaMajor: 'Upper Valley',
  },
  {
    ListingId: 'EP2026-1234',
    ListingKey: 'EP2026-1234-KEY',
    ModificationTimestamp: '2026-02-11T08:00:00Z',
    ListOfficeName: 'Keller Williams El Paso',
    ListOfficeKey: 'KW001',
    ListAgentFullName: 'Michael Rodriguez',
    ListAgentKey: 'MR001',
    ListAgentMLSID: 'EP-MR-2023',
    StandardStatus: 'Active',
    ListPrice: 315000,
    UnparsedAddress: '1234 Desert Bloom Way',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79928',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    BathroomsFull: 2,
    BathroomsHalf: 1,
    LivingArea: 2400,
    LotSizeAcres: 0.25,
    YearBuilt: 2024,
    Media: [
      { MediaURL: '/images/properties/home-3.jpg', Order: 1 },
    ],
    Latitude: 31.6943,
    Longitude: -106.2050,
    PublicRemarks: 'Brand new home in fast-growing Horizon City. Energy-efficient construction, modern open design with community amenities. Perfect for first-time buyers looking for value.',
    DaysOnMarket: 3,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Microwave', 'Range', 'Refrigerator', 'Disposal'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Attached'],
    SubdivisionName: 'Desert Bloom',
    MLSAreaMajor: 'Horizon City',
  },
  {
    ListingId: 'EP2026-9876',
    ListingKey: 'EP2026-9876-KEY',
    ModificationTimestamp: '2026-02-08T16:45:00Z',
    ListOfficeName: 'The Right Move Real Estate Group',
    ListOfficeKey: 'RIGHTMOVE001',
    ListAgentFullName: 'Lorena Ontiveros-Ortega',
    ListAgentKey: 'LO001',
    ListAgentMLSID: 'EP-LO-2024',
    StandardStatus: 'Active',
    ListPrice: 850000,
    UnparsedAddress: '9876 Championship Dr',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79934',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 5,
    BathroomsTotalInteger: 5,
    BathroomsFull: 4,
    BathroomsHalf: 1,
    LivingArea: 4500,
    LotSizeAcres: 0.45,
    YearBuilt: 2019,
    Media: [
      { MediaURL: '/images/properties/home-4.jpg', Order: 1 },
    ],
    Latitude: 31.9123,
    Longitude: -106.6234,
    PublicRemarks: 'Exceptional luxury estate in prestigious Cimarron. Custom finishes throughout, chef\'s kitchen, theater room, stunning pool and spa. Golf course community with exclusive amenities.',
    DaysOnMarket: 21,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Built-In Oven', 'Cooktop', 'Dishwasher', 'Disposal', 'Microwave', 'Refrigerator', 'Wine Cooler'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['3-Car Garage', 'Attached'],
    PoolFeatures: ['Heated', 'In Ground', 'Spa/Hot Tub'],
    SubdivisionName: 'Cimarron',
    MLSAreaMajor: 'Westside',
  },
  {
    ListingId: 'EP2026-3456',
    ListingKey: 'EP2026-3456-KEY',
    ModificationTimestamp: '2026-02-10T09:00:00Z',
    ListOfficeName: 'RE/MAX Real Estate Services',
    ListOfficeKey: 'REMAX001',
    ListAgentFullName: 'Sarah Martinez',
    ListAgentKey: 'SM001',
    ListAgentMLSID: 'EP-SM-2022',
    StandardStatus: 'Pending',
    ListPrice: 285000,
    UnparsedAddress: '3456 Sunset Ridge Ln',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79912',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1650,
    LotSizeAcres: 0.18,
    YearBuilt: 2010,
    Media: [
      { MediaURL: '/images/properties/home-5.jpg', Order: 1 },
    ],
    Latitude: 31.8456,
    Longitude: -106.6055,
    PublicRemarks: 'Perfect starter home in desirable Westside location. Move-in ready with updated bathrooms, new HVAC system, and low-maintenance yard. Near top-rated schools and shopping.',
    DaysOnMarket: 5,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['Covered Parking'],
    SubdivisionName: 'Sunset Ridge',
    MLSAreaMajor: 'Westside',
  },
  {
    ListingId: 'EP2026-5670',
    ListingKey: 'EP2026-5670-KEY',
    ModificationTimestamp: '2026-02-07T11:20:00Z',
    ListOfficeName: 'Coldwell Banker El Paso',
    ListOfficeKey: 'CB001',
    ListAgentFullName: 'David Chen',
    ListAgentKey: 'DC001',
    ListAgentMLSID: 'EP-DC-2021',
    StandardStatus: 'Active',
    ListPrice: 395000,
    UnparsedAddress: '567 Downtown Plaza #203',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79901',
    PropertyType: 'Townhouse',
    PropertySubType: 'Townhouse',
    BedroomsTotal: 2,
    BathroomsTotalInteger: 3,
    BathroomsFull: 2,
    BathroomsHalf: 1,
    LivingArea: 1850,
    YearBuilt: 2021,
    Media: [
      { MediaURL: '/images/properties/home-6.jpg', Order: 1 },
    ],
    Latitude: 31.7587,
    Longitude: -106.4869,
    PublicRemarks: 'Contemporary townhouse in vibrant downtown El Paso. Rooftop terrace with mountain views, walkable to restaurants, entertainment, and the arts district.',
    DaysOnMarket: 15,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['Attached Garage'],
    SubdivisionName: 'Downtown Lofts',
    MLSAreaMajor: 'Downtown',
  },
  {
    ListingId: 'EP2026-7890',
    ListingKey: 'EP2026-7890-KEY',
    ModificationTimestamp: '2026-02-09T15:30:00Z',
    ListOfficeName: 'The Right Move Real Estate Group',
    ListOfficeKey: 'RIGHTMOVE001',
    ListAgentFullName: 'Lorena Ontiveros-Ortega',
    ListAgentKey: 'LO001',
    ListAgentMLSID: 'EP-LO-2024',
    StandardStatus: 'Active',
    ListPrice: 475000,
    UnparsedAddress: '7890 Franklin Heights Ct',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79912',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    BathroomsFull: 3,
    LivingArea: 2800,
    LotSizeAcres: 0.3,
    YearBuilt: 2021,
    Media: [
      { MediaURL: '/images/properties/home-7.jpg', Order: 1 },
    ],
    Latitude: 31.8390,
    Longitude: -106.5900,
    PublicRemarks: 'Stunning modern home with panoramic Franklin Mountain views. Open concept living with high ceilings, designer kitchen with waterfall island, and resort-style backyard.',
    DaysOnMarket: 7,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Built-In Oven', 'Cooktop', 'Dishwasher', 'Disposal', 'Microwave', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Attached'],
    PoolFeatures: ['In Ground'],
    SubdivisionName: 'Franklin Heights',
    MLSAreaMajor: 'Westside',
  },
  {
    ListingId: 'EP2026-2345',
    ListingKey: 'EP2026-2345-KEY',
    ModificationTimestamp: '2026-02-08T12:00:00Z',
    ListOfficeName: 'Keller Williams El Paso',
    ListOfficeKey: 'KW001',
    ListAgentFullName: 'Michael Rodriguez',
    ListAgentKey: 'MR001',
    ListAgentMLSID: 'EP-MR-2023',
    StandardStatus: 'Active',
    ListPrice: 245000,
    UnparsedAddress: '2345 Mesa Garden Dr',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79936',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1500,
    LotSizeAcres: 0.15,
    YearBuilt: 2005,
    Media: [
      { MediaURL: '/images/properties/home-8.jpg', Order: 1 },
    ],
    Latitude: 31.7750,
    Longitude: -106.3300,
    PublicRemarks: 'Well-maintained home in established East El Paso neighborhood. Updated kitchen and bathrooms, spacious backyard, convenient location near Ft. Bliss and shopping centers.',
    DaysOnMarket: 18,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage'],
    SubdivisionName: 'Mesa Gardens',
    MLSAreaMajor: 'East El Paso',
  },
  {
    ListingId: 'EP2026-6543',
    ListingKey: 'EP2026-6543-KEY',
    ModificationTimestamp: '2026-02-10T13:45:00Z',
    ListOfficeName: 'RE/MAX Real Estate Services',
    ListOfficeKey: 'REMAX001',
    ListAgentFullName: 'Sarah Martinez',
    ListAgentKey: 'SM001',
    ListAgentMLSID: 'EP-SM-2022',
    StandardStatus: 'Active',
    ListPrice: 520000,
    UnparsedAddress: '6543 Kern Place Ave',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79902',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    BathroomsFull: 2,
    BathroomsHalf: 1,
    LivingArea: 2900,
    LotSizeAcres: 0.35,
    YearBuilt: 1948,
    Media: [
      { MediaURL: '/images/properties/home-9.jpg', Order: 1 },
    ],
    Latitude: 31.7800,
    Longitude: -106.4950,
    PublicRemarks: 'Beautifully restored historic home in the coveted Kern Place neighborhood. Original hardwood floors, updated systems, chef\'s kitchen, and mature landscaping on a spacious lot.',
    DaysOnMarket: 10,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Disposal', 'Microwave', 'Range', 'Refrigerator'],
    ArchitecturalStyle: 'Spanish Colonial',
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Detached'],
    SubdivisionName: 'Kern Place',
    MLSAreaMajor: 'Central',
  },
  {
    ListingId: 'EP2026-4320',
    ListingKey: 'EP2026-4320-KEY',
    ModificationTimestamp: '2026-02-06T10:00:00Z',
    ListOfficeName: 'Coldwell Banker El Paso',
    ListOfficeKey: 'CB001',
    ListAgentFullName: 'David Chen',
    ListAgentKey: 'DC001',
    ListAgentMLSID: 'EP-DC-2021',
    StandardStatus: 'Active',
    ListPrice: 189000,
    UnparsedAddress: '4320 Hondo Pass Dr',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79904',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1350,
    LotSizeAcres: 0.12,
    YearBuilt: 1998,
    Media: [
      { MediaURL: '/images/properties/home-10.jpg', Order: 1 },
    ],
    Latitude: 31.8200,
    Longitude: -106.4400,
    PublicRemarks: 'Affordable Northeast El Paso home ideal for first-time buyers or investors. Well-maintained with updated flooring, fresh paint, and convenient access to US-54.',
    DaysOnMarket: 25,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['1-Car Garage'],
    SubdivisionName: 'Northeast Heights',
    MLSAreaMajor: 'Northeast',
  },
  {
    ListingId: 'EP2026-5501',
    ListingKey: 'EP2026-5501-KEY',
    ModificationTimestamp: '2026-02-11T07:30:00Z',
    ListOfficeName: 'The Right Move Real Estate Group',
    ListOfficeKey: 'RIGHTMOVE001',
    ListAgentFullName: 'Lorena Ontiveros-Ortega',
    ListAgentKey: 'LO001',
    ListAgentMLSID: 'EP-LO-2024',
    StandardStatus: 'Active',
    ListPrice: 340000,
    UnparsedAddress: '5501 Canutillo Pass Rd',
    City: 'Canutillo',
    StateOrProvince: 'TX',
    PostalCode: '79835',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 2,
    LivingArea: 2200,
    LotSizeAcres: 0.75,
    YearBuilt: 2018,
    Media: [
      { MediaURL: '/images/properties/home-11.jpg', Order: 1 },
    ],
    Latitude: 31.9120,
    Longitude: -106.5990,
    PublicRemarks: 'Spacious home on a large lot in quiet Canutillo. Country living minutes from the city. Open floor plan, covered patio, and room for horses or workshops.',
    DaysOnMarket: 2,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'RV Parking'],
    SubdivisionName: 'Canutillo Estates',
    MLSAreaMajor: 'Canutillo',
  },
  {
    ListingId: 'EP2026-6789',
    ListingKey: 'EP2026-6789-KEY',
    ModificationTimestamp: '2026-02-09T09:15:00Z',
    ListOfficeName: 'Keller Williams El Paso',
    ListOfficeKey: 'KW001',
    ListAgentFullName: 'Michael Rodriguez',
    ListAgentKey: 'MR001',
    ListAgentMLSID: 'EP-MR-2023',
    StandardStatus: 'Pending',
    ListPrice: 275000,
    UnparsedAddress: '6789 Socorro Rd',
    City: 'Socorro',
    StateOrProvince: 'TX',
    PostalCode: '79927',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1800,
    LotSizeAcres: 0.20,
    YearBuilt: 2020,
    Media: [
      { MediaURL: '/images/properties/home-12.jpg', Order: 1 },
    ],
    Latitude: 31.6550,
    Longitude: -106.3000,
    PublicRemarks: 'Nearly new home in growing Socorro community. Energy-efficient construction, open layout, stainless steel appliances, and community park access.',
    DaysOnMarket: 9,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Disposal', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Attached'],
    SubdivisionName: 'Mission Valley',
    MLSAreaMajor: 'Socorro',
  },
  {
    ListingId: 'EP2026-1100',
    ListingKey: 'EP2026-1100-KEY',
    ModificationTimestamp: '2026-02-10T17:00:00Z',
    ListOfficeName: 'RE/MAX Real Estate Services',
    ListOfficeKey: 'REMAX001',
    ListAgentFullName: 'Sarah Martinez',
    ListAgentKey: 'SM001',
    ListAgentMLSID: 'EP-SM-2022',
    StandardStatus: 'Active',
    ListPrice: 675000,
    UnparsedAddress: '1100 Vista Del Sol Dr',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79934',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 4,
    BathroomsFull: 3,
    BathroomsHalf: 1,
    LivingArea: 3200,
    LotSizeAcres: 0.35,
    YearBuilt: 2020,
    Media: [
      { MediaURL: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop&q=80', Order: 1 },
    ],
    Latitude: 31.8500,
    Longitude: -106.5700,
    PublicRemarks: 'Breathtaking contemporary home with panoramic Franklin Mountain views. Smart home technology, gourmet kitchen with quartz countertops, resort-style backyard with heated pool.',
    DaysOnMarket: 12,
    VirtualTourURLUnbranded: 'https://my.matterport.com/show/?m=example1',
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Built-In Oven', 'Cooktop', 'Dishwasher', 'Disposal', 'Microwave', 'Refrigerator', 'Wine Cooler'],
    Cooling: 'Central Air',
    Heating: 'Radiant Floor',
    ParkingFeatures: ['3-Car Garage', 'Attached'],
    PoolFeatures: ['Heated', 'In Ground'],
    SubdivisionName: 'Vista del Sol',
    MLSAreaMajor: 'Westside',
  },
  {
    ListingId: 'EP2026-2200',
    ListingKey: 'EP2026-2200-KEY',
    ModificationTimestamp: '2026-02-07T14:30:00Z',
    ListOfficeName: 'Coldwell Banker El Paso',
    ListOfficeKey: 'CB001',
    ListAgentFullName: 'David Chen',
    ListAgentKey: 'DC001',
    ListAgentMLSID: 'EP-DC-2021',
    StandardStatus: 'Closed',
    ListPrice: 310000,
    UnparsedAddress: '2200 N Mesa St #405',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79902',
    PropertyType: 'Condo',
    PropertySubType: 'Condominium',
    BedroomsTotal: 2,
    BathroomsTotalInteger: 2,
    LivingArea: 1200,
    YearBuilt: 2022,
    Media: [
      { MediaURL: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop&q=80', Order: 1 },
    ],
    Latitude: 31.7780,
    Longitude: -106.5050,
    PublicRemarks: 'Modern condo in the heart of UTEP area. Floor-to-ceiling windows, designer finishes, rooftop pool, and secure parking. Steps from campus and Kern Place dining.',
    DaysOnMarket: 30,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['Underground Parking'],
    SubdivisionName: 'Mesa Tower',
    MLSAreaMajor: 'Central',
  },
  {
    ListingId: 'EP2026-3300',
    ListingKey: 'EP2026-3300-KEY',
    ModificationTimestamp: '2026-02-11T10:15:00Z',
    ListOfficeName: 'The Right Move Real Estate Group',
    ListOfficeKey: 'RIGHTMOVE001',
    ListAgentFullName: 'Lorena Ontiveros-Ortega',
    ListAgentKey: 'LO001',
    ListAgentMLSID: 'EP-LO-2024',
    StandardStatus: 'Active',
    ListPrice: 198000,
    UnparsedAddress: '3300 Tierra Este Rd',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79938',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 3,
    BathroomsTotalInteger: 2,
    LivingArea: 1400,
    LotSizeAcres: 0.14,
    YearBuilt: 2016,
    Media: [
      { MediaURL: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop&q=80', Order: 1 },
    ],
    Latitude: 31.7300,
    Longitude: -106.2100,
    PublicRemarks: 'Great opportunity in East El Paso! Well-kept home with open layout, granite countertops, tile throughout, and covered back patio. Easy access to I-10 and Fort Bliss.',
    DaysOnMarket: 1,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Attached'],
    SubdivisionName: 'Tierra Este',
    MLSAreaMajor: 'East El Paso',
  },
  {
    ListingId: 'EP2026-4400',
    ListingKey: 'EP2026-4400-KEY',
    ModificationTimestamp: '2026-02-05T08:00:00Z',
    ListOfficeName: 'Keller Williams El Paso',
    ListOfficeKey: 'KW001',
    ListAgentFullName: 'Michael Rodriguez',
    ListAgentKey: 'MR001',
    ListAgentMLSID: 'EP-MR-2023',
    StandardStatus: 'Active',
    ListPrice: 425000,
    UnparsedAddress: '4400 Shadow Mountain Trl',
    City: 'El Paso',
    StateOrProvince: 'TX',
    PostalCode: '79934',
    PropertyType: 'Residential',
    PropertySubType: 'Single Family Residence',
    BedroomsTotal: 4,
    BathroomsTotalInteger: 3,
    BathroomsFull: 2,
    BathroomsHalf: 1,
    LivingArea: 2650,
    LotSizeAcres: 0.28,
    YearBuilt: 2017,
    Media: [
      { MediaURL: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop&q=80', Order: 1 },
    ],
    Latitude: 31.8550,
    Longitude: -106.5750,
    PublicRemarks: 'Beautiful Westside home on Shadow Mountain Trail. Open floor plan, gourmet kitchen, large master suite with mountain views. Minutes from La Union and The Fountains at Farah.',
    DaysOnMarket: 14,
    InternetEntireListingDisplay: true,
    InternetAddressDisplay: true,
    VOWAddressDisplay: true,
    Appliances: ['Dishwasher', 'Disposal', 'Microwave', 'Range', 'Refrigerator'],
    Cooling: 'Central Air',
    Heating: 'Central',
    ParkingFeatures: ['2-Car Garage', 'Attached'],
    SubdivisionName: 'Shadow Mountain',
    MLSAreaMajor: 'Westside',
  },
];

// Convert RESO MLSListing to consumer-safe PropertyDisplayData
export function transformMLSToDisplay(listing: MLSListing): PropertyDisplayData {
  const statusMap: Record<string, 'For Sale' | 'Pending' | 'Sold'> = {
    Active: 'For Sale',
    Pending: 'Pending',
    Closed: 'Sold',
  };

  return {
    id: listing.ListingId,
    mlsNumber: listing.ListingId,
    listOfficeName: listing.ListOfficeName,
    listAgentName: listing.ListAgentFullName,
    status: statusMap[listing.StandardStatus] || 'For Sale',
    price: listing.ListPrice,
    address: listing.UnparsedAddress,
    city: listing.City,
    state: listing.StateOrProvince,
    zip: listing.PostalCode,
    neighborhood: listing.MLSAreaMajor || listing.SubdivisionName || 'El Paso',
    beds: listing.BedroomsTotal,
    baths: listing.BathroomsTotalInteger,
    sqft: listing.LivingArea,
    lotSize: listing.LotSizeAcres,
    yearBuilt: listing.YearBuilt,
    propertyType: listing.PropertySubType || listing.PropertyType,
    images: listing.Media
      .sort((a, b) => a.Order - b.Order)
      .map((m) => m.MediaURL),
    virtualTour: listing.VirtualTourURLUnbranded,
    description: listing.PublicRemarks || '',
    features: [
      ...(listing.Appliances || []),
      ...(listing.ParkingFeatures || []),
      ...(listing.PoolFeatures || []),
      ...(listing.Cooling ? [`Cooling: ${listing.Cooling}`] : []),
      ...(listing.Heating ? [`Heating: ${listing.Heating}`] : []),
      ...(listing.ArchitecturalStyle ? [listing.ArchitecturalStyle] : []),
    ],
    daysOnMarket: listing.DaysOnMarket || 0,
    lastUpdated: listing.ModificationTimestamp,
    latitude: listing.Latitude,
    longitude: listing.Longitude,
  };
}

// Get filtered listings (respects opt-out flags)
export function getListings(filters?: PropertyFilters): PropertyDisplayData[] {
  let listings = MOCK_MLS_LISTINGS.filter(isListingDisplayable);

  if (filters) {
    if (filters.minPrice !== undefined) {
      listings = listings.filter((l) => l.ListPrice >= filters.minPrice!);
    }
    if (filters.maxPrice !== undefined) {
      listings = listings.filter((l) => l.ListPrice <= filters.maxPrice!);
    }
    if (filters.minBeds !== undefined) {
      listings = listings.filter((l) => l.BedroomsTotal >= filters.minBeds!);
    }
    if (filters.minBaths !== undefined) {
      listings = listings.filter((l) => l.BathroomsTotalInteger >= filters.minBaths!);
    }
    if (filters.propertyTypes?.length) {
      listings = listings.filter((l) =>
        filters.propertyTypes!.includes(l.PropertyType) ||
        filters.propertyTypes!.includes(l.PropertySubType || '')
      );
    }
    if (filters.neighborhoods?.length) {
      listings = listings.filter((l) =>
        filters.neighborhoods!.includes(l.MLSAreaMajor || '')
      );
    }
    if (filters.status?.length) {
      const statusMap: Record<string, string> = {
        'For Sale': 'Active',
        Pending: 'Pending',
        Sold: 'Closed',
      };
      const mlsStatuses = filters.status.map((s) => statusMap[s] || s);
      listings = listings.filter((l) => mlsStatuses.includes(l.StandardStatus));
    }
    if (filters.searchTerm) {
      const term = filters.searchTerm.toLowerCase();
      listings = listings.filter(
        (l) =>
          l.UnparsedAddress.toLowerCase().includes(term) ||
          l.City.toLowerCase().includes(term) ||
          (l.MLSAreaMajor || '').toLowerCase().includes(term) ||
          (l.SubdivisionName || '').toLowerCase().includes(term)
      );
    }
  }

  return listings.map(transformMLSToDisplay);
}

// Get single listing by ID
export function getListingById(id: string): PropertyDisplayData | null {
  const listing = MOCK_MLS_LISTINGS.find((l) => l.ListingId === id);
  if (!listing || !isListingDisplayable(listing)) return null;
  return transformMLSToDisplay(listing);
}

// Get all unique neighborhoods from displayable listings
export function getNeighborhoods(): string[] {
  const neighborhoods = new Set(
    MOCK_MLS_LISTINGS
      .filter(isListingDisplayable)
      .map((l) => l.MLSAreaMajor || '')
      .filter(Boolean)
  );
  return Array.from(neighborhoods).sort();
}
