// Seed data for automation features — drip sequences, calendar campaigns, checklists, email templates

export const SEED_DRIP_SEQUENCES = [
  {
    name: 'Speed-to-Lead',
    description: '7-day, 7-touch outreach when a new lead registers. Replaces CINC Speed-to-Lead (3 days) + Lorena Intro.',
    trigger: 'new_lead',
    is_active: true,
    steps: [
      { type: 'sms', delay_days: 0, template_body: 'Hi {{first_name}}! This is Lorena with Casas en El Paso. I saw you were looking at properties — anything specific catching your eye?', template_body_es: 'Hola {{first_name}}! Soy Lorena de Casas en El Paso. Vi que estabas buscando propiedades, ¿hay algo que te haya llamado la atención?' },
      { type: 'email', delay_days: 1, template_subject: 'Welcome to Your El Paso Home Search!', template_subject_es: '¡Bienvenido/a a tu búsqueda de casa en El Paso!', template_body: 'Hi {{first_name}},\n\nWelcome! I\'m Lorena Ontiveros-Ortega, your El Paso real estate specialist. I\'d love to help you find your perfect home.\n\nHere are some featured listings that match your interests. Let me know if any catch your eye!\n\nBest,\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Bienvenido/a! Soy Lorena Ontiveros-Ortega, tu especialista en bienes raíces en El Paso. Me encantaría ayudarte a encontrar tu casa ideal.\n\nAquí tienes algunas propiedades destacadas que pueden interesarte. ¡Dime si alguna te llama la atención!\n\nSaludos,\nLorena' },
      { type: 'sms', delay_days: 2, template_body: 'Hey {{first_name}}, just checking in! Did you get a chance to look at those listings? Happy to answer any questions.', template_body_es: 'Hola {{first_name}}, ¡solo quería saber cómo vas! ¿Pudiste ver las propiedades que te mandé? Con gusto te respondo cualquier pregunta.' },
      { type: 'sms', delay_days: 3, template_body: '{{first_name}}, new listings just hit the market in El Paso! Want me to send you the details?', template_body_es: '{{first_name}}, ¡acaban de salir nuevas propiedades en El Paso! ¿Quieres que te mande los detalles?' },
      { type: 'email', delay_days: 4, template_subject: 'El Paso Buyer Guide: Everything You Need to Know', template_subject_es: 'Guía para comprar casa en El Paso: Todo lo que necesitas saber', template_body: 'Hi {{first_name}},\n\nWhether you\'re a first-time buyer or relocating to El Paso, here\'s your complete guide to the home buying process.\n\nLet me know if you\'d like to schedule a quick call to discuss your goals!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nYa sea que estés comprando tu primera casa o mudándote a El Paso, aquí tienes tu guía completa del proceso de compra.\n\n¡Dime si te gustaría agendar una llamada rápida para platicar sobre tus planes!\n\nLorena' },
      { type: 'sms', delay_days: 5, template_body: 'Hi {{first_name}}! I have some great properties to show this weekend. Would you like to schedule a tour?', template_body_es: '¡Hola {{first_name}}! Tengo unas propiedades muy buenas para enseñarte este fin de semana. ¿Te gustaría agendar un recorrido?' },
      { type: 'sms', delay_days: 7, template_body: '{{first_name}}, hope you\'re having a great week! I\'m here whenever you\'re ready to start your home search. Just text back!', template_body_es: '{{first_name}}, ¡espero que tengas una buena semana! Aquí estoy cuando quieras empezar a buscar casa. ¡Solo responde este mensaje!' },
    ],
  },
  {
    name: 'New Buyer Welcome',
    description: '30-day nurture sequence for new buyer leads. Builds trust with value content.',
    trigger: 'status_change:contacted',
    is_active: true,
    steps: [
      { type: 'sms', delay_days: 0, template_body: 'Hi {{first_name}}! Lorena here. Excited to help you find your dream home in El Paso. What neighborhoods are you most interested in?', template_body_es: '¡Hola {{first_name}}! Soy Lorena. Estoy muy emocionada de ayudarte a encontrar tu casa ideal en El Paso. ¿Qué colonias te interesan más?' },
      { type: 'email', delay_days: 2, template_subject: 'Top Listings in Your Favorite Areas', template_subject_es: 'Las mejores propiedades en tus áreas favoritas', template_body: 'Hi {{first_name}},\n\nI pulled together the top 5 listings in your preferred areas. Take a look and let me know which ones you\'d like to tour!\n\nBest,\nLorena', template_body_es: 'Hola {{first_name}},\n\nTe preparé las 5 mejores propiedades en las áreas que te gustan. ¡Échalas un vistazo y dime cuáles te gustaría visitar!\n\nSaludos,\nLorena' },
      { type: 'sms', delay_days: 5, template_body: '{{first_name}}, a new listing just came on in your area — want the details?', template_body_es: '{{first_name}}, acaba de salir una nueva propiedad en tu área, ¿quieres los detalles?' },
      { type: 'email', delay_days: 8, template_subject: '5 Tips for First-Time Buyers in El Paso', template_subject_es: '5 consejos para comprar tu primera casa en El Paso', template_body: 'Hi {{first_name}},\n\nBuying your first home is exciting! Here are 5 tips to make the process smooth:\n\n1. Get pre-approved early\n2. Know your must-haves vs. nice-to-haves\n3. Research neighborhoods thoroughly\n4. Don\'t skip the inspection\n5. Work with a local expert (that\'s me!)\n\nQuestions? I\'m here to help.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Comprar tu primera casa es emocionante! Aquí van 5 consejos para que todo salga bien:\n\n1. Consigue tu pre-aprobación temprano\n2. Define lo que necesitas vs. lo que te gustaría\n3. Investiga bien las colonias\n4. No te saltes la inspección\n5. Trabaja con una experta local (¡esa soy yo!)\n\n¿Preguntas? Aquí estoy para ayudarte.\n\nLorena' },
      { type: 'sms', delay_days: 12, template_body: 'Hey {{first_name}}! I have 3 homes ready to show this weekend. Want to book a tour?', template_body_es: '¡Hola {{first_name}}! Tengo 3 casas listas para enseñar este fin de semana. ¿Quieres agendar un recorrido?' },
      { type: 'sms', delay_days: 15, template_body: 'Reminder: Call {{first_name}} to schedule showings', template_body_es: 'Recordatorio: Llamar a {{first_name}} para agendar visitas' },
      { type: 'email', delay_days: 20, template_subject: 'El Paso Market Update', template_subject_es: 'Actualización del mercado de El Paso', template_body: 'Hi {{first_name}},\n\nHere\'s what\'s happening in the El Paso market this month — trends, price changes, and new opportunities.\n\nLet\'s chat about what this means for your search!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nAquí te cuento lo que está pasando en el mercado de El Paso este mes: tendencias, cambios de precio y nuevas oportunidades.\n\n¡Platiquemos sobre lo que esto significa para tu búsqueda!\n\nLorena' },
      { type: 'sms', delay_days: 25, template_body: '{{first_name}}, new price drops on properties you might like! Want the updated list?', template_body_es: '{{first_name}}, ¡bajaron los precios de propiedades que te pueden gustar! ¿Quieres la lista actualizada?' },
    ],
  },
  {
    name: 'Seller CMA Nurture',
    description: '14-day sequence for sellers who requested a CMA or home valuation.',
    trigger: 'cma_request',
    is_active: true,
    steps: [
      { type: 'sms', delay_days: 0, template_body: '{{first_name}}, your home analysis is ready! Check your email for the full report.', template_body_es: '{{first_name}}, ¡tu análisis de casa está listo! Revisa tu correo para ver el reporte completo.' },
      { type: 'email', delay_days: 2, template_subject: 'Your Home Value Report', template_subject_es: 'El reporte del valor de tu casa', template_body: 'Hi {{first_name}},\n\nAttached is your Comparative Market Analysis. Based on recent sales in your area, here are the key takeaways.\n\nI\'d love to discuss your options — would you like to schedule a quick call?\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nAquí tienes tu Análisis Comparativo de Mercado. Basado en ventas recientes en tu área, estos son los puntos clave.\n\nMe encantaría platicar sobre tus opciones, ¿te gustaría agendar una llamada rápida?\n\nLorena' },
      { type: 'sms', delay_days: 5, template_body: '{{first_name}}, 3 similar homes sold this month in your area. The market is moving — want to chat?', template_body_es: '{{first_name}}, 3 casas parecidas a la tuya se vendieron este mes en tu área. El mercado se está moviendo, ¿platicamos?' },
      { type: 'sms', delay_days: 7, template_body: 'Reminder: Call {{first_name}} for listing consultation', template_body_es: 'Recordatorio: Llamar a {{first_name}} para consulta de venta' },
      { type: 'email', delay_days: 10, template_subject: 'Ready to Sell? Here\'s Your Next Steps', template_subject_es: '¿Lista/o para vender? Estos son los pasos a seguir', template_body: 'Hi {{first_name}},\n\nWhen you\'re ready to list, here\'s what the process looks like:\n\n1. Listing consultation (free!)\n2. Professional photos & staging tips\n3. MLS listing + marketing\n4. Showings & open houses\n5. Offer review & negotiation\n\nLet\'s get started whenever you\'re ready.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nCuando estés listo/a para poner tu casa en venta, así funciona el proceso:\n\n1. Consulta de venta (¡gratis!)\n2. Fotos profesionales y consejos de presentación\n3. Publicación en MLS + marketing\n4. Visitas y casas abiertas\n5. Revisión de ofertas y negociación\n\nEmpezamos cuando tú quieras.\n\nLorena' },
    ],
  },
  {
    name: 'Re-engagement',
    description: 'Win back cold leads who have gone quiet. Triggered when score drops below 30.',
    trigger: 'score_below_30',
    is_active: true,
    steps: [
      { type: 'email', delay_days: 0, template_subject: 'Still Thinking About El Paso Real Estate?', template_subject_es: '¿Todavía piensas en comprar casa en El Paso?', template_body: 'Hi {{first_name}},\n\nIt\'s been a while! The El Paso market has some exciting new listings. Here\'s a quick update on what\'s changed.\n\nWhenever you\'re ready to start looking again, I\'m here.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Ha pasado un tiempo! El mercado de El Paso tiene nuevas propiedades muy interesantes. Aquí te va un resumen rápido de lo que ha cambiado.\n\nCuando quieras volver a buscar, aquí estoy.\n\nLorena' },
      { type: 'sms', delay_days: 7, template_body: '{{first_name}}, prices dropped on 2 properties in your favorite areas! Want the details?', template_body_es: '{{first_name}}, ¡bajaron los precios en 2 propiedades en tus áreas favoritas! ¿Quieres los detalles?' },
      { type: 'email', delay_days: 14, template_subject: 'Price Drops in Your Favorite Areas', template_subject_es: 'Bajaron precios en tus áreas favoritas', template_body: 'Hi {{first_name}},\n\nGood news — several properties in the areas you like have seen price reductions. It could be the perfect time to take another look.\n\nLet me know if you\'d like to schedule a tour!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nBuenas noticias: varias propiedades en las áreas que te gustan han bajado de precio. Podría ser el momento perfecto para darles otra mirada.\n\n¡Dime si te gustaría agendar un recorrido!\n\nLorena' },
      { type: 'sms', delay_days: 21, template_body: 'Hey {{first_name}}, still interested in El Paso real estate? I\'d love to help whenever you\'re ready. Just text back!', template_body_es: 'Hola {{first_name}}, ¿todavía te interesa comprar casa en El Paso? Me encantaría ayudarte cuando estés listo/a. ¡Solo responde este mensaje!' },
    ],
  },
  {
    name: 'Post-Closing',
    description: '1-year follow-up for closed deals. Builds referrals, requests reviews, tracks equity. Replaces CINC Past Client Follow Up + Google Review.',
    trigger: 'status_change:past_client',
    is_active: true,
    steps: [
      { type: 'sms', delay_days: 1, template_body: 'Congratulations {{first_name}}! Welcome to your new home! If you need anything during move-in, don\'t hesitate to reach out.', template_body_es: '¡Felicidades {{first_name}}! ¡Bienvenido/a a tu nuevo hogar! Si necesitas algo durante la mudanza, no dudes en escribirme.' },
      { type: 'email', delay_days: 7, template_subject: 'New Homeowner Tips & Resources', template_subject_es: 'Consejos y recursos para tu nueva casa', template_body: 'Hi {{first_name}},\n\nCongrats again! Here are some helpful resources for your first weeks:\n\n- Change of address checklist\n- Utility setup guide for El Paso\n- Recommended local contractors\n- Home maintenance calendar\n\nEnjoy your new home!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Felicidades otra vez! Aquí tienes recursos útiles para tus primeras semanas:\n\n- Lista para cambio de dirección\n- Guía para activar servicios en El Paso\n- Contratistas locales recomendados\n- Calendario de mantenimiento del hogar\n\n¡Disfruta tu nueva casa!\n\nLorena' },
      { type: 'sms', delay_days: 30, template_body: 'Hi {{first_name}}! How are you settling in? If you had a great experience, I\'d love a quick Google review — it helps other families find their home too!', template_body_es: '¡Hola {{first_name}}! ¿Cómo te va en tu nueva casa? Si tuviste una buena experiencia, me encantaría que dejaras una reseña en Google. ¡Ayuda a que otras familias encuentren su hogar también!' },
      { type: 'email', delay_days: 60, template_subject: 'Leave a Review & Help Other Families', template_subject_es: 'Deja una reseña y ayuda a otras familias', template_body: 'Hi {{first_name}},\n\nI hope you\'re enjoying your new home! If our experience together was positive, a quick Google review would mean the world to me.\n\nIt only takes 30 seconds and helps other families find trusted help.\n\nThank you!\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Espero que estés disfrutando tu nueva casa! Si nuestra experiencia juntos fue positiva, una reseña rápida en Google significaría mucho para mí.\n\nSolo toma 30 segundos y ayuda a otras familias a encontrar ayuda de confianza.\n\n¡Gracias!\nLorena' },
      { type: 'email', delay_days: 90, template_subject: 'Know Someone Buying or Selling?', template_subject_es: '¿Conoces a alguien que quiera comprar o vender?', template_body: 'Hi {{first_name}},\n\nHope you\'re loving your home! If you know anyone looking to buy or sell in El Paso, I\'d be honored if you sent them my way.\n\nReferrals are the best compliment!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Espero que estés feliz en tu casa! Si conoces a alguien que quiera comprar o vender en El Paso, sería un honor que me recomendaras.\n\n¡Las recomendaciones son el mejor cumplido!\n\nLorena' },
      { type: 'email', delay_days: 180, template_subject: 'Your Home Equity Update', template_subject_es: 'Actualización del valor de tu casa', template_body: 'Hi {{first_name}},\n\nIt\'s been 6 months! Here\'s a quick look at how your home value has changed and what\'s happening in your neighborhood.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Ya pasaron 6 meses! Aquí tienes un resumen de cómo ha cambiado el valor de tu casa y lo que está pasando en tu colonia.\n\nLorena' },
      { type: 'sms', delay_days: 365, template_body: 'Happy home anniversary {{first_name}}! It\'s been a year. Want a free equity update on your property?', template_body_es: '¡Feliz aniversario de tu casa {{first_name}}! Ya pasó un año. ¿Quieres un reporte gratis del valor de tu propiedad?' },
    ],
  },
  {
    name: 'Monthly Market Report',
    description: 'Quarterly market update emails with El Paso trends. Replaces CINC Monthly Market Report (13% open rate, 2,093 completed).',
    trigger: 'enrollment',
    is_active: true,
    steps: [
      { type: 'email', delay_days: 30, template_subject: 'Your Monthly El Paso Market Report', template_subject_es: 'Tu reporte mensual del mercado de El Paso', template_body: 'Hi {{first_name}},\n\nHere\'s your monthly El Paso real estate market report! This month\'s highlights:\n\n- Median home prices and trends\n- New listings in your preferred areas\n- Days on market analysis\n- Interest rate update\n\nWant to discuss what this means for you? Just reply!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Aquí tienes tu reporte mensual del mercado de bienes raíces de El Paso! Lo más destacado de este mes:\n\n- Precios promedio y tendencias\n- Nuevas propiedades en tus áreas preferidas\n- Análisis de días en el mercado\n- Actualización de tasas de interés\n\n¿Quieres platicar sobre lo que esto significa para ti? ¡Solo responde!\n\nLorena' },
      { type: 'email', delay_days: 60, template_subject: 'Market Update: What\'s Changed This Month', template_subject_es: 'Actualización del mercado: Lo que cambió este mes', template_body: 'Hi {{first_name}},\n\nAnother month, another market update! Here\'s what\'s happening in El Paso real estate and how it affects your goals.\n\nLet me know if you\'d like a personalized analysis.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Otro mes, otra actualización del mercado! Esto es lo que está pasando en bienes raíces en El Paso y cómo afecta tus planes.\n\nDime si quieres un análisis personalizado.\n\nLorena' },
      { type: 'email', delay_days: 90, template_subject: 'Quarterly Market Recap & Forecast', template_subject_es: 'Resumen trimestral del mercado y pronóstico', template_body: 'Hi {{first_name}},\n\nHere\'s your quarterly recap of the El Paso housing market — where we\'ve been and where we\'re heading.\n\nReady to make a move? I\'m here to help.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nAquí tienes tu resumen trimestral del mercado de El Paso: de dónde venimos y hacia dónde vamos.\n\n¿Listo/a para dar el paso? Aquí estoy para ayudarte.\n\nLorena' },
    ],
  },
  {
    name: 'HomePulse Seller Nurture',
    description: '190-day, 7-touch seller nurture sequence. Replaces CINC HomePulse Boost (134 leads enrolled).',
    trigger: 'enrollment',
    is_active: true,
    steps: [
      { type: 'email', delay_days: 0, template_subject: 'Your Home Value Report is Ready!', template_subject_es: '¡Tu reporte del valor de tu casa está listo!', template_body: 'Hi {{first_name}},\n\nGreat news — your personalized home value report is ready! Based on recent sales and market data, here\'s what your home could be worth today.\n\nWant a detailed analysis? I\'m happy to provide a free CMA.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Buenas noticias! Tu reporte personalizado del valor de tu casa está listo. Basado en ventas recientes y datos del mercado, esto es lo que tu casa podría valer hoy.\n\n¿Quieres un análisis más detallado? Con gusto te preparo un CMA gratis.\n\nLorena' },
      { type: 'email', delay_days: 30, template_subject: 'Your Home Value Has Changed', template_subject_es: 'El valor de tu casa ha cambiado', template_body: 'Hi {{first_name}},\n\nThe market has shifted since your last report. Here\'s an updated look at your home\'s estimated value and what\'s happening in your neighborhood.\n\nCurious about selling? Let\'s chat.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nEl mercado ha cambiado desde tu último reporte. Aquí tienes una mirada actualizada al valor estimado de tu casa y lo que está pasando en tu colonia.\n\n¿Te interesa vender? Platiquemos.\n\nLorena' },
      { type: 'sms', delay_days: 60, template_body: '{{first_name}}, homes in your area are selling fast! Want an updated value report on your property?', template_body_es: '{{first_name}}, ¡las casas en tu área se están vendiendo rápido! ¿Quieres un reporte actualizado del valor de tu propiedad?' },
      { type: 'email', delay_days: 90, template_subject: 'Market Shift Alert: Your Neighborhood', template_subject_es: 'Alerta de cambio en el mercado: Tu colonia', template_body: 'Hi {{first_name}},\n\nBig changes in your area! Several homes similar to yours have sold recently. Here\'s what that means for your property\'s value.\n\nThinking about selling? Now could be a great time.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Grandes cambios en tu área! Varias casas parecidas a la tuya se han vendido recientemente. Esto es lo que significa para el valor de tu propiedad.\n\n¿Estás pensando en vender? Ahora podría ser un buen momento.\n\nLorena' },
      { type: 'email', delay_days: 120, template_subject: 'Seasonal Market Update for Homeowners', template_subject_es: 'Actualización de temporada para propietarios', template_body: 'Hi {{first_name}},\n\nSeasonal trends affect home values. Here\'s how the current season is impacting El Paso real estate and what it means for homeowners like you.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nLas tendencias de temporada afectan el valor de las casas. Así es como la temporada actual está impactando el mercado de El Paso y lo que significa para propietarios como tú.\n\nLorena' },
      { type: 'sms', delay_days: 150, template_body: '{{first_name}}, your home\'s value may have increased! Want me to run a quick analysis?', template_body_es: '{{first_name}}, ¡el valor de tu casa puede haber subido! ¿Quieres que haga un análisis rápido?' },
      { type: 'email', delay_days: 190, template_subject: 'Your Annual Home Value Review', template_subject_es: 'Tu revisión anual del valor de tu casa', template_body: 'Hi {{first_name}},\n\nIt\'s time for your annual home value review! Here\'s a comprehensive look at how your property has performed over the past months.\n\nWhether you\'re thinking of selling or just want to stay informed, I\'m here to help.\n\nLorena', template_body_es: 'Hola {{first_name}},\n\n¡Es hora de tu revisión anual del valor de tu casa! Aquí tienes un resumen completo de cómo ha ido tu propiedad en los últimos meses.\n\nYa sea que pienses vender o solo quieras estar informado/a, aquí estoy para ayudarte.\n\nLorena' },
    ],
  },
  {
    name: 'Lender Introduction',
    description: '4-day sequence introducing Emmanuel (loan officer) for financing. Replaces CINC Needs Financing - Lender Intro.',
    trigger: 'enrollment',
    is_active: true,
    steps: [
      { type: 'email', delay_days: 0, template_subject: 'Meet Emmanuel - Your Mortgage Expert', template_subject_es: 'Conoce a Emmanuel - Tu experto en hipotecas', template_body: 'Hi {{first_name}},\n\nI\'d like to introduce you to Emmanuel Ortega, our trusted mortgage partner at American Pacific Mortgage. He specializes in helping El Paso buyers find the best financing options.\n\nEmmanuel will reach out to discuss pre-approval and what you qualify for. No obligation!\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nQuiero presentarte a Emmanuel Ortega, nuestro socio de confianza en American Pacific Mortgage. Él se especializa en ayudar a compradores en El Paso a encontrar las mejores opciones de financiamiento.\n\nEmmanuel se pondrá en contacto contigo para hablar sobre pre-aprobación y para qué calificas. ¡Sin compromiso!\n\nLorena' },
      { type: 'sms', delay_days: 2, template_body: '{{first_name}}, did you connect with Emmanuel about financing? He can get you pre-approved quickly so we can start viewing homes!', template_body_es: '{{first_name}}, ¿ya te comunicaste con Emmanuel sobre el financiamiento? Él te puede pre-aprobar rápido para que empecemos a ver casas.' },
      { type: 'email', delay_days: 4, template_subject: 'Financing Resources for El Paso Buyers', template_subject_es: 'Recursos de financiamiento para compradores en El Paso', template_body: 'Hi {{first_name}},\n\nHere are some helpful financing resources:\n\n- FHA loans (3.5% down)\n- VA loans (0% down for military)\n- Conventional loans\n- Down payment assistance programs\n\nEmmanuel can walk you through all options. Ready to get started?\n\nLorena', template_body_es: 'Hola {{first_name}},\n\nAquí tienes recursos útiles de financiamiento:\n\n- Préstamos FHA (3.5% de enganche)\n- Préstamos VA (0% de enganche para militares)\n- Préstamos convencionales\n- Programas de asistencia para enganche\n\nEmmanuel puede explicarte todas las opciones. ¿Listo/a para empezar?\n\nLorena' },
    ],
  },
];

export const SEED_CALENDAR_CAMPAIGNS = [
  { name: 'New Year', description: 'New Year, new home! Kick off the year with fresh listings.', description_es: '¡Año nuevo, casa nueva! Empieza el año con nuevas propiedades.', month: 1, day: 1, channel: 'sms' as const, is_active: true },
  { name: 'Valentine\'s Day', description: 'Fall in love with your dream home this February.', description_es: 'Enamórate de tu casa ideal este febrero.', month: 2, day: 14, channel: 'email' as const, is_active: true },
  { name: 'Easter', description: 'Spring into your new home! Fresh listings for the season.', description_es: '¡La primavera trae nuevas casas! Propiedades frescas para la temporada.', month: 4, day: null, channel: 'email' as const, is_active: true },
  { name: 'Mother\'s Day', description: 'Mom deserves the best — including the perfect home.', description_es: 'Mamá merece lo mejor, incluyendo la casa perfecta.', month: 5, day: null, channel: 'sms' as const, is_active: true },
  { name: 'Father\'s Day', description: 'Celebrate dad this June! Home is where the family is.', description_es: '¡Celebra a papá este junio! El hogar es donde está la familia.', month: 6, day: null, channel: 'sms' as const, is_active: true },
  { name: 'July 4th', description: 'Celebrate freedom in your own home! Independence Day specials.', description_es: '¡Celebra la libertad en tu propio hogar! Ofertas del Día de la Independencia.', month: 7, day: 4, channel: 'sms' as const, is_active: true },
  { name: 'Labor Day', description: 'End of summer, start of a new chapter. Great time to buy!', description_es: 'Fin del verano, inicio de un nuevo capítulo. ¡Gran momento para comprar!', month: 9, day: null, channel: 'email' as const, is_active: true },
  { name: 'Halloween', description: 'Don\'t be scared of the market — spooky good deals await!', description_es: 'No le tengas miedo al mercado, ¡hay ofertas espantosamente buenas!', month: 10, day: 31, channel: 'email' as const, is_active: true },
  { name: 'Veterans Day', description: 'Thank you for your service! Special resources for military buyers and VA loans.', description_es: '¡Gracias por su servicio! Recursos especiales para compradores militares y préstamos VA.', month: 11, day: 11, channel: 'email' as const, is_active: true },
  { name: 'Thanksgiving', description: 'Grateful for your home. Market update and holiday wishes.', description_es: 'Agradecidos por nuestro hogar. Actualización del mercado y buenos deseos.', month: 11, day: null, channel: 'email' as const, is_active: true },
  { name: 'Christmas', description: 'Happy holidays! Year-end market recap and new year preview.', description_es: '¡Felices fiestas! Resumen del mercado y lo que viene para el nuevo año.', month: 12, day: 25, channel: 'sms' as const, is_active: true },
  { name: 'New Year\'s Eve', description: 'Ring in the new year! Looking forward to helping you in the year ahead.', description_es: '¡Recibe el año nuevo! Estoy lista para ayudarte en el año que viene.', month: 12, day: 31, channel: 'sms' as const, is_active: true },
  { name: 'Birthday', description: 'Per-lead birthday greeting. Uses lead birthday from profile.', description_es: 'Felicitación de cumpleaños personalizada. Usa la fecha de cumpleaños del perfil.', month: 1, day: null, channel: 'sms' as const, is_active: true },
  { name: 'Home Anniversary', description: 'Per-lead home purchase anniversary with equity update.', description_es: 'Aniversario de compra de casa con actualización del valor.', month: 1, day: null, channel: 'email' as const, is_active: true },
];

export const SEED_CHECKLIST_TEMPLATES = [
  {
    name: 'Buyer Closing Checklist',
    description: 'Complete checklist for guiding buyers through the closing process.',
    items: [
      { label: 'Get pre-approval letter from lender', completed: false },
      { label: 'Schedule home inspection', completed: false },
      { label: 'Review inspection report', completed: false },
      { label: 'Order property appraisal', completed: false },
      { label: 'Complete title search', completed: false },
      { label: 'Secure homeowner\'s insurance', completed: false },
      { label: 'Schedule final walkthrough', completed: false },
      { label: 'Review closing disclosure', completed: false },
      { label: 'Arrange wire transfer / cashier\'s check', completed: false },
      { label: 'Sign closing documents and get keys', completed: false },
    ],
  },
  {
    name: 'Seller Listing Checklist',
    description: 'Steps to prepare a home for listing and sale.',
    items: [
      { label: 'Complete home valuation / CMA', completed: false },
      { label: 'Declutter and stage home', completed: false },
      { label: 'Schedule professional photography', completed: false },
      { label: 'Sign listing agreement', completed: false },
      { label: 'Publish MLS listing', completed: false },
      { label: 'Schedule open house dates', completed: false },
      { label: 'Review and compare offers', completed: false },
      { label: 'Accept offer and begin closing', completed: false },
    ],
  },
  {
    name: 'New Lead Onboarding',
    description: 'Initial steps for onboarding a new lead into the CRM.',
    items: [
      { label: 'Make initial contact call', completed: false },
      { label: 'Complete needs assessment', completed: false },
      { label: 'Set up MLS search criteria', completed: false },
      { label: 'Send initial property recommendations', completed: false },
      { label: 'Schedule first property showing', completed: false },
      { label: 'Follow-up call after first showing', completed: false },
    ],
  },
];

export const SEED_EMAIL_TEMPLATES = [
  {
    name: 'Welcome Email',
    subject: 'Welcome to Casas En El Paso!',
    subject_es: '¡Bienvenido/a a Casas En El Paso!',
    body_html: '<h2>Welcome, {{first_name}}!</h2><p>Thank you for starting your home search with us. I\'m Lorena Ontiveros-Ortega, your dedicated El Paso real estate specialist.</p><p>I\'ll be sending you personalized listings and market updates. In the meantime, feel free to browse our latest properties.</p><p>Best regards,<br/>Lorena</p>',
    body_html_es: '<h2>¡Bienvenido/a, {{first_name}}!</h2><p>Gracias por empezar tu búsqueda de casa con nosotros. Soy Lorena Ontiveros-Ortega, tu especialista en bienes raíces en El Paso.</p><p>Te estaré mandando propiedades personalizadas y actualizaciones del mercado. Mientras tanto, siéntete libre de explorar nuestras propiedades más recientes.</p><p>Saludos,<br/>Lorena</p>',
    body_text: 'Welcome, {{first_name}}! Thank you for starting your home search with us. I\'m Lorena, your El Paso real estate specialist. I\'ll be sending you personalized listings and market updates. Best, Lorena',
    body_text_es: '¡Bienvenido/a, {{first_name}}! Gracias por empezar tu búsqueda de casa con nosotros. Soy Lorena, tu especialista en bienes raíces en El Paso. Te mandaré propiedades y actualizaciones del mercado. Saludos, Lorena',
    category: 'onboarding',
    language: 'en',
  },
  {
    name: 'Market Update',
    subject: 'El Paso Real Estate Market Update',
    subject_es: 'Actualización del mercado de bienes raíces de El Paso',
    body_html: '<h2>Monthly Market Update</h2><p>Hi {{first_name}},</p><p>Here\'s what\'s happening in the El Paso real estate market this month. Median prices, new listings, and market trends — all tailored to your search.</p><p>Let\'s chat about what this means for you!</p><p>Lorena</p>',
    body_html_es: '<h2>Actualización mensual del mercado</h2><p>Hola {{first_name}},</p><p>Esto es lo que está pasando en el mercado de bienes raíces de El Paso este mes. Precios promedio, nuevas propiedades y tendencias del mercado, todo personalizado para tu búsqueda.</p><p>¡Platiquemos sobre lo que esto significa para ti!</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, here\'s your monthly El Paso market update with median prices, new listings, and trends. Let\'s chat about what this means for you! Lorena',
    body_text_es: 'Hola {{first_name}}, aquí tienes tu actualización mensual del mercado de El Paso con precios, nuevas propiedades y tendencias. ¡Platiquemos sobre lo que esto significa para ti! Lorena',
    category: 'nurture',
    language: 'en',
  },
  {
    name: 'Price Drop Alert',
    subject: 'Price Drop on Properties You\'ll Love!',
    subject_es: '¡Bajaron los precios en propiedades que te van a encantar!',
    body_html: '<h2>Price Drops Alert!</h2><p>Hi {{first_name}},</p><p>Great news — several properties in your favorite areas have seen price reductions. Now might be the perfect time to schedule a tour!</p><p>Check out the updated listings and let me know which ones interest you.</p><p>Lorena</p>',
    body_html_es: '<h2>¡Alerta de baja de precios!</h2><p>Hola {{first_name}},</p><p>Buenas noticias: varias propiedades en tus áreas favoritas han bajado de precio. ¡Ahora podría ser el momento perfecto para agendar un recorrido!</p><p>Mira las propiedades actualizadas y dime cuáles te interesan.</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, prices dropped on properties in your favorite areas! Check out the updated listings. Lorena',
    body_text_es: 'Hola {{first_name}}, ¡bajaron los precios en propiedades en tus áreas favoritas! Mira las propiedades actualizadas. Lorena',
    category: 'alert',
    language: 'en',
  },
  {
    name: 'Showing Confirmation',
    subject: 'Your Property Showing is Confirmed!',
    subject_es: '¡Tu visita a la propiedad está confirmada!',
    body_html: '<h2>Showing Confirmed!</h2><p>Hi {{first_name}},</p><p>Your showing has been confirmed for <strong>{{showing_date}}</strong> at <strong>{{showing_time}}</strong>.</p><p><strong>Address:</strong> {{showing_address}}</p><p>See you there!</p><p>Lorena</p>',
    body_html_es: '<h2>¡Visita confirmada!</h2><p>Hola {{first_name}},</p><p>Tu visita ha sido confirmada para el <strong>{{showing_date}}</strong> a las <strong>{{showing_time}}</strong>.</p><p><strong>Dirección:</strong> {{showing_address}}</p><p>¡Nos vemos ahí!</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, your showing is confirmed for {{showing_date}} at {{showing_time}} at {{showing_address}}. See you there! Lorena',
    body_text_es: 'Hola {{first_name}}, tu visita está confirmada para el {{showing_date}} a las {{showing_time}} en {{showing_address}}. ¡Nos vemos ahí! Lorena',
    category: 'transactional',
    language: 'en',
  },
  {
    name: 'Review Request',
    subject: 'How Was Your Experience?',
    subject_es: '¿Cómo fue tu experiencia?',
    body_html: '<h2>We\'d Love Your Feedback!</h2><p>Hi {{first_name}},</p><p>Congratulations on your new home! I hope you\'re settling in well.</p><p>If you had a great experience, I\'d be incredibly grateful if you could leave a quick review. It helps other families find their way home too.</p><p>Thank you so much!</p><p>Lorena</p>',
    body_html_es: '<h2>¡Nos encantaría saber tu opinión!</h2><p>Hola {{first_name}},</p><p>¡Felicidades por tu nueva casa! Espero que te estés instalando bien.</p><p>Si tuviste una buena experiencia, te agradecería mucho si pudieras dejar una reseña rápida. Ayuda a que otras familias encuentren su hogar también.</p><p>¡Muchas gracias!</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, congratulations on your new home! If you had a great experience, I\'d love a quick review. Thank you! Lorena',
    body_text_es: 'Hola {{first_name}}, ¡felicidades por tu nueva casa! Si tuviste una buena experiencia, me encantaría una reseña rápida. ¡Gracias! Lorena',
    category: 'post-closing',
    language: 'en',
  },
  {
    name: 'Monthly Market Report',
    subject: 'Your Monthly El Paso Market Report',
    subject_es: 'Tu reporte mensual del mercado de El Paso',
    body_html: '<h2>Monthly Market Report</h2><p>Hi {{first_name}},</p><p>Here\'s your monthly El Paso real estate market report!</p><p><strong>This month\'s highlights:</strong></p><ul><li>Median home prices and trends</li><li>New listings in your preferred areas</li><li>Days on market analysis</li><li>Interest rate update</li></ul><p>Want to discuss what this means for you? Just reply!</p><p>Lorena</p>',
    body_html_es: '<h2>Reporte mensual del mercado</h2><p>Hola {{first_name}},</p><p>¡Aquí tienes tu reporte mensual del mercado de bienes raíces de El Paso!</p><p><strong>Lo más destacado de este mes:</strong></p><ul><li>Precios promedio de casas y tendencias</li><li>Nuevas propiedades en tus áreas preferidas</li><li>Análisis de días en el mercado</li><li>Actualización de tasas de interés</li></ul><p>¿Quieres platicar sobre lo que esto significa para ti? ¡Solo responde!</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, here\'s your monthly El Paso market report! Highlights: median prices, new listings, days on market, and interest rates. Want to discuss? Just reply! Lorena',
    body_text_es: 'Hola {{first_name}}, ¡aquí tienes tu reporte mensual del mercado de El Paso! Destacado: precios promedio, nuevas propiedades, días en el mercado y tasas de interés. ¿Platicamos? ¡Solo responde! Lorena',
    category: 'nurture',
    language: 'en',
  },
  {
    name: 'HomePulse Initial Report',
    subject: 'Your Home Value Report is Ready!',
    subject_es: '¡Tu reporte del valor de tu casa está listo!',
    body_html: '<h2>Your Home Value Report</h2><p>Hi {{first_name}},</p><p>Great news — your personalized home value report is ready! Based on recent sales and market data, here\'s what your home could be worth today.</p><p>Want a detailed Comparative Market Analysis? I\'m happy to provide one for free.</p><p>Lorena</p>',
    body_html_es: '<h2>Tu reporte del valor de tu casa</h2><p>Hola {{first_name}},</p><p>¡Buenas noticias! Tu reporte personalizado del valor de tu casa está listo. Basado en ventas recientes y datos del mercado, esto es lo que tu casa podría valer hoy.</p><p>¿Quieres un Análisis Comparativo de Mercado detallado? Con gusto te lo preparo gratis.</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, your home value report is ready! Based on recent sales and market data, here\'s what your home could be worth. Want a detailed CMA? It\'s free! Lorena',
    body_text_es: 'Hola {{first_name}}, ¡tu reporte del valor de tu casa está listo! Basado en ventas recientes y datos del mercado, esto es lo que tu casa podría valer. ¿Quieres un CMA detallado? ¡Es gratis! Lorena',
    category: 'seller',
    language: 'en',
  },
  {
    name: 'HomePulse Update',
    subject: 'Your Home Value Has Changed',
    subject_es: 'El valor de tu casa ha cambiado',
    body_html: '<h2>Home Value Update</h2><p>Hi {{first_name}},</p><p>The market has shifted since your last report. Here\'s an updated look at your home\'s estimated value and what\'s happening in your neighborhood.</p><p>Curious about selling? Let\'s chat about your options.</p><p>Lorena</p>',
    body_html_es: '<h2>Actualización del valor de tu casa</h2><p>Hola {{first_name}},</p><p>El mercado ha cambiado desde tu último reporte. Aquí tienes una mirada actualizada al valor estimado de tu casa y lo que está pasando en tu colonia.</p><p>¿Te interesa vender? Platiquemos sobre tus opciones.</p><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, the market has shifted! Here\'s an updated look at your home value and neighborhood trends. Curious about selling? Let\'s chat. Lorena',
    body_text_es: 'Hola {{first_name}}, ¡el mercado ha cambiado! Aquí tienes una mirada actualizada al valor de tu casa y tendencias de tu colonia. ¿Te interesa vender? Platiquemos. Lorena',
    category: 'seller',
    language: 'en',
  },
  {
    name: 'Lender Introduction',
    subject: 'Meet Emmanuel - Your Mortgage Expert',
    subject_es: 'Conoce a Emmanuel - Tu experto en hipotecas',
    body_html: '<h2>Your Financing Partner</h2><p>Hi {{first_name}},</p><p>I\'d like to introduce you to <strong>Emmanuel Ortega</strong>, our trusted mortgage partner at American Pacific Mortgage. He specializes in helping El Paso buyers find the best financing options.</p><p>Emmanuel will reach out to discuss pre-approval and what you qualify for. No obligation!</p><p>Options available:</p><ul><li>FHA loans (3.5% down)</li><li>VA loans (0% down for military)</li><li>Conventional loans</li><li>Down payment assistance programs</li></ul><p>Lorena</p>',
    body_html_es: '<h2>Tu socio de financiamiento</h2><p>Hola {{first_name}},</p><p>Quiero presentarte a <strong>Emmanuel Ortega</strong>, nuestro socio de confianza en American Pacific Mortgage. Él se especializa en ayudar a compradores en El Paso a encontrar las mejores opciones de financiamiento.</p><p>Emmanuel se pondrá en contacto contigo para hablar sobre pre-aprobación y para qué calificas. ¡Sin compromiso!</p><p>Opciones disponibles:</p><ul><li>Préstamos FHA (3.5% de enganche)</li><li>Préstamos VA (0% de enganche para militares)</li><li>Préstamos convencionales</li><li>Programas de asistencia para enganche</li></ul><p>Lorena</p>',
    body_text: 'Hi {{first_name}}, I\'d like to introduce Emmanuel Ortega, our mortgage partner at American Pacific Mortgage. He can help with FHA, VA, conventional loans, and down payment assistance. No obligation! Lorena',
    body_text_es: 'Hola {{first_name}}, quiero presentarte a Emmanuel Ortega, nuestro socio en American Pacific Mortgage. Te puede ayudar con préstamos FHA, VA, convencionales y asistencia para enganche. ¡Sin compromiso! Lorena',
    category: 'financing',
    language: 'en',
  },
  {
    name: 'Birthday Greeting',
    subject: 'Happy Birthday from Lorena!',
    subject_es: '¡Feliz cumpleaños de parte de Lorena!',
    body_html: '<h2>Happy Birthday, {{first_name}}!</h2><p>Wishing you a wonderful birthday filled with joy and celebration!</p><p>As your real estate agent, I\'m always here if you need anything — whether it\'s a home question or just a friendly chat.</p><p>Have an amazing day!</p><p>Lorena</p>',
    body_html_es: '<h2>¡Feliz cumpleaños, {{first_name}}!</h2><p>¡Te deseo un cumpleaños maravilloso lleno de alegría y celebración!</p><p>Como tu agente de bienes raíces, siempre estoy aquí si necesitas algo, ya sea una pregunta sobre tu casa o simplemente una plática amigable.</p><p>¡Que tengas un día increíble!</p><p>Lorena</p>',
    body_text: 'Happy Birthday, {{first_name}}! Wishing you a wonderful day. I\'m always here if you need anything real estate related. Have an amazing day! Lorena',
    body_text_es: '¡Feliz cumpleaños, {{first_name}}! Te deseo un día maravilloso. Siempre estoy aquí si necesitas algo relacionado con bienes raíces. ¡Que tengas un día increíble! Lorena',
    category: 'celebration',
    language: 'en',
  },
];
