// Seed data for development — 20 leads, 15 properties, messages, showings, sequences

export const AGENT_ID = '00000000-0000-0000-0000-000000000001'; // Dev seed UUID — replaced with real agent UUID after signup

// ============================================
// 20 LEADS with El Paso Hispanic names
// ============================================
export const SEED_LEADS = [
  // HOT (80-100)
  { first_name: 'Maria', last_name: 'Gonzalez', email: 'maria.gonzalez@gmail.com', phone: '(915) 555-0101', score: 92, source: 'website' as const, status: 'appointment_set' as const, tags: ['VA Loan', 'Eastlake'], preferred_language: 'es', budget_min: 250000, budget_max: 350000, preferred_areas: ['Eastlake', 'Pebble Hills'], property_type: 'single_family', timeline: '1-3 months' },
  { first_name: 'Carlos', last_name: 'Mendez', email: 'carlos.mendez@yahoo.com', phone: '(915) 555-0102', score: 85, source: 'referral' as const, status: 'contacted' as const, tags: ['First-Time', 'FHA'], preferred_language: 'en', budget_min: 180000, budget_max: 250000, preferred_areas: ['Mesa Hills', 'Westside'], property_type: 'single_family', timeline: '1-3 months' },
  { first_name: 'Rosa', last_name: 'Martinez', email: 'rosa.martinez@outlook.com', phone: '(915) 555-0103', score: 81, source: 'zillow' as const, status: 'appointment_set' as const, tags: ['Investor', 'Multi-Family'], preferred_language: 'es', budget_min: 150000, budget_max: 300000, preferred_areas: ['Central El Paso', 'Sunset Heights'], property_type: 'multi_family', timeline: 'ASAP' },

  // WARM (50-79)
  { first_name: 'Ana', last_name: 'Rodriguez', email: 'ana.rodriguez@gmail.com', phone: '(915) 555-0104', score: 72, source: 'website' as const, status: 'contacted' as const, tags: ['Growing Family'], preferred_language: 'en', budget_min: 200000, budget_max: 300000, preferred_areas: ['Pebble Hills', 'Northeast'], property_type: 'single_family', timeline: '3-6 months' },
  { first_name: 'Luis', last_name: 'Hernandez', email: 'luis.hernandez@hotmail.com', phone: '(915) 555-0105', score: 68, source: 'referral' as const, status: 'contacted' as const, tags: ['Military', 'Fort Bliss'], preferred_language: 'en', budget_min: 200000, budget_max: 280000, preferred_areas: ['Northeast', 'Horizon City'], property_type: 'single_family', timeline: '1-3 months' },
  { first_name: 'Sofia', last_name: 'Morales', email: 'sofia.morales@gmail.com', phone: '(915) 555-0106', score: 61, source: 'social' as const, status: 'contacted' as const, tags: ['Downsizing'], preferred_language: 'es', budget_min: 150000, budget_max: 220000, preferred_areas: ['Upper Valley', 'Canutillo'], property_type: 'single_family', timeline: '6+ months' },
  { first_name: 'Diego', last_name: 'Torres', email: 'diego.torres@yahoo.com', phone: '(915) 555-0107', score: 55, source: 'website' as const, status: 'new_lead' as const, tags: ['First-Time'], preferred_language: 'en', budget_min: 160000, budget_max: 230000, preferred_areas: ['Westside'], property_type: 'single_family', timeline: '3-6 months' },
  { first_name: 'Isabella', last_name: 'Reyes', email: 'isabella.reyes@gmail.com', phone: '(915) 555-0108', score: 52, source: 'open_house' as const, status: 'contacted' as const, tags: ['Relocating'], preferred_language: 'en', budget_min: 280000, budget_max: 400000, preferred_areas: ['Montecillo', 'Kern Place'], property_type: 'single_family', timeline: '1-3 months' },

  // COOL (20-49)
  { first_name: 'Pedro', last_name: 'Gutierrez', email: 'pedro.gutierrez@gmail.com', phone: '(915) 555-0109', score: 45, source: 'website' as const, status: 'new_lead' as const, tags: ['Investor'], preferred_language: 'es', budget_min: 100000, budget_max: 200000, preferred_areas: ['Central El Paso'], property_type: 'single_family', timeline: '6+ months' },
  { first_name: 'Carmen', last_name: 'Flores', email: 'carmen.flores@yahoo.com', phone: '(915) 555-0110', score: 38, source: 'zillow' as const, status: 'new_lead' as const, tags: ['Retiree'], preferred_language: 'es', budget_min: 120000, budget_max: 180000, preferred_areas: ['Upper Valley'], property_type: 'single_family', timeline: '6+ months' },
  { first_name: 'Miguel', last_name: 'Sanchez', email: 'miguel.sanchez@hotmail.com', phone: '(915) 555-0111', score: 32, source: 'referral' as const, status: 'new_lead' as const, tags: ['First-Time', 'FHA'], preferred_language: 'en', budget_min: 150000, budget_max: 220000, preferred_areas: ['Northeast'], property_type: 'single_family', timeline: '6+ months' },
  { first_name: 'Elena', last_name: 'Castillo', email: 'elena.castillo@gmail.com', phone: '(915) 555-0112', score: 28, source: 'website' as const, status: 'new_lead' as const, tags: ['Growing Family'], preferred_language: 'en', budget_min: 200000, budget_max: 300000, preferred_areas: ['Eastlake'], property_type: 'single_family', timeline: 'Just Looking' },
  { first_name: 'Roberto', last_name: 'Ramirez', email: 'roberto.ramirez@outlook.com', phone: '(915) 555-0113', score: 42, source: 'social' as const, status: 'contacted' as const, tags: ['Military'], preferred_language: 'en', budget_min: 180000, budget_max: 260000, preferred_areas: ['Horizon City', 'Northeast'], property_type: 'single_family', timeline: '3-6 months' },
  { first_name: 'Lucia', last_name: 'Ortiz', email: 'lucia.ortiz@gmail.com', phone: '(915) 555-0114', score: 35, source: 'website' as const, status: 'new_lead' as const, tags: ['Downsizing'], preferred_language: 'es', budget_min: 130000, budget_max: 190000, preferred_areas: ['Westside', 'Canutillo'], property_type: 'condo', timeline: '6+ months' },
  { first_name: 'Andres', last_name: 'Vargas', email: 'andres.vargas@yahoo.com', phone: '(915) 555-0115', score: 24, source: 'cold_call' as const, status: 'new_lead' as const, tags: ['Investor'], preferred_language: 'en', budget_min: 100000, budget_max: 160000, preferred_areas: ['Central El Paso'], property_type: 'multi_family', timeline: 'Just Looking' },
  { first_name: 'Patricia', last_name: 'Rivera', email: 'patricia.rivera@gmail.com', phone: '(915) 555-0116', score: 40, source: 'open_house' as const, status: 'contacted' as const, tags: ['First-Time'], preferred_language: 'en', budget_min: 170000, budget_max: 240000, preferred_areas: ['Mesa Hills'], property_type: 'single_family', timeline: '3-6 months' },

  // COLD (0-19)
  { first_name: 'Fernando', last_name: 'Cruz', email: 'fernando.cruz@hotmail.com', phone: '(915) 555-0117', score: 15, source: 'website' as const, status: 'new_lead' as const, tags: [], preferred_language: 'en', budget_min: 150000, budget_max: 250000, preferred_areas: [], property_type: 'single_family', timeline: 'Just Looking' },
  { first_name: 'Gloria', last_name: 'Jimenez', email: 'gloria.jimenez@yahoo.com', phone: '(915) 555-0118', score: 8, source: 'website' as const, status: 'new_lead' as const, tags: [], preferred_language: 'es', budget_min: 100000, budget_max: 180000, preferred_areas: [], property_type: null, timeline: null },
  { first_name: 'Manuel', last_name: 'Delgado', email: 'manuel.delgado@gmail.com', phone: '(915) 555-0119', score: 4, source: 'cinc' as const, status: 'new_lead' as const, tags: [], preferred_language: 'en', budget_min: null, budget_max: null, preferred_areas: [], property_type: null, timeline: null },
  { first_name: 'Beatriz', last_name: 'Salazar', email: 'beatriz.salazar@outlook.com', phone: '(915) 555-0120', score: 12, source: 'cinc' as const, status: 'new_lead' as const, tags: ['Retiree'], preferred_language: 'es', budget_min: 120000, budget_max: 170000, preferred_areas: ['Upper Valley'], property_type: 'single_family', timeline: '6+ months' },
];

// ============================================
// 15 EL PASO PROPERTIES ($150K-$500K)
// ============================================
export const SEED_PROPERTIES = [
  { address: '1234 Mesa Hills Dr', zip: '79912', price: 285000, bedrooms: 4, bathrooms: 2.5, sqft: 2200, year_built: 2005, property_type: 'single_family', neighborhood: 'Mesa Hills', features: ['Pool', 'Updated Kitchen', '2-Car Garage'], description: 'Beautiful 4-bedroom home in Mesa Hills with a pool and updated kitchen.' },
  { address: '5678 Pebble Hills Blvd', zip: '79936', price: 320000, bedrooms: 4, bathrooms: 3, sqft: 2500, year_built: 2015, property_type: 'single_family', neighborhood: 'Pebble Hills', features: ['Open Floor Plan', 'Smart Home', 'Mountain Views'], description: 'Modern 4-bedroom with smart home features and stunning mountain views.' },
  { address: '910 Eastlake Dr', zip: '79938', price: 245000, bedrooms: 3, bathrooms: 2, sqft: 1800, year_built: 2018, property_type: 'single_family', neighborhood: 'Eastlake', features: ['Energy Efficient', 'Community Pool', 'New Build'], description: 'Nearly new 3-bedroom in the desirable Eastlake community.' },
  { address: '2345 Westside Ave', zip: '79932', price: 195000, bedrooms: 3, bathrooms: 2, sqft: 1600, year_built: 1998, property_type: 'single_family', neighborhood: 'Westside', features: ['Large Yard', 'Covered Patio', 'New Roof'], description: 'Charming 3-bedroom with a large yard, perfect for families.' },
  { address: '6789 Northeast Blvd', zip: '79934', price: 265000, bedrooms: 4, bathrooms: 2, sqft: 2100, year_built: 2010, property_type: 'single_family', neighborhood: 'Northeast', features: ['Corner Lot', 'RV Parking', 'Updated Bathrooms'], description: 'Spacious 4-bedroom on a corner lot with RV parking.' },
  { address: '1111 Horizon City Rd', zip: '79928', price: 175000, bedrooms: 3, bathrooms: 2, sqft: 1400, year_built: 2012, property_type: 'single_family', neighborhood: 'Horizon City', features: ['Desert Landscaping', 'Open Kitchen', 'Near Schools'], description: 'Affordable 3-bedroom in growing Horizon City community.' },
  { address: '3333 Canutillo Way', zip: '79835', price: 225000, bedrooms: 3, bathrooms: 2, sqft: 1700, year_built: 2008, property_type: 'single_family', neighborhood: 'Canutillo', features: ['Quiet Street', 'Upgraded Flooring', 'Storage Shed'], description: 'Peaceful 3-bedroom in Canutillo with upgrades throughout.' },
  { address: '4444 Upper Valley Rd', zip: '79922', price: 425000, bedrooms: 5, bathrooms: 3.5, sqft: 3200, year_built: 2002, property_type: 'single_family', neighborhood: 'Upper Valley', features: ['Horse Property', 'Casita', 'Irrigated Land'], description: 'Stunning 5-bedroom on irrigated land with a private casita.' },
  { address: '5555 Central El Paso St', zip: '79901', price: 155000, bedrooms: 2, bathrooms: 1, sqft: 1100, year_built: 1955, property_type: 'single_family', neighborhood: 'Central El Paso', features: ['Historic District', 'Character Home', 'Near UTEP'], description: 'Historic 2-bedroom near UTEP with original character and charm.' },
  { address: '6666 Montecillo Plaza', zip: '79912', price: 350000, bedrooms: 3, bathrooms: 2.5, sqft: 1900, year_built: 2020, property_type: 'townhome', neighborhood: 'Montecillo', features: ['Rooftop Terrace', 'Walk to Restaurants', 'Modern Design'], description: 'Modern townhome in vibrant Montecillo with rooftop terrace.' },
  { address: '7777 Westway Dr', zip: '79932', price: 185000, bedrooms: 3, bathrooms: 2, sqft: 1500, year_built: 2006, property_type: 'single_family', neighborhood: 'Westway', features: ['Fireplace', 'Tile Floors', 'Covered Parking'], description: 'Well-maintained 3-bedroom in Westway with fireplace and tile floors.' },
  { address: '8888 Socorro Rd', zip: '79927', price: 165000, bedrooms: 3, bathrooms: 2, sqft: 1350, year_built: 2014, property_type: 'single_family', neighborhood: 'Socorro', features: ['Newer Construction', 'Granite Counters', 'HOA Pool'], description: 'Newer 3-bedroom with granite counters in Socorro.' },
  { address: '9999 Kern Place Ln', zip: '79902', price: 475000, bedrooms: 4, bathrooms: 3, sqft: 2800, year_built: 1940, property_type: 'single_family', neighborhood: 'Kern Place', features: ['Historic', 'Remodeled', 'Tree-Lined Street'], description: 'Beautifully remodeled historic home in prestigious Kern Place.' },
  { address: '1212 Coronado Hills Dr', zip: '79912', price: 310000, bedrooms: 4, bathrooms: 2.5, sqft: 2400, year_built: 2008, property_type: 'single_family', neighborhood: 'Coronado Hills', features: ['Gated Community', 'Stainless Appliances', 'Office'], description: '4-bedroom in gated Coronado Hills with dedicated office space.' },
  { address: '1313 Sunset Heights Ave', zip: '79902', price: 220000, bedrooms: 3, bathrooms: 2, sqft: 1600, year_built: 1925, property_type: 'single_family', neighborhood: 'Sunset Heights', features: ['Historic District', 'Original Hardwood', 'Mountain Views'], description: 'Classic Sunset Heights home with original hardwood and mountain views.' },
];
