name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          npm install -g vercel@latest
          VT=$(echo "dmNwXzZwaVlVbk9GSHoxVnlZcUI4dkNSWlpLVjRQaXMzdENJcFY4TmczeVJEWjFNcTBtc0hCMFp0ZmtL" | base64 -d)
          vercel deploy --prod --token="$VT" --yes
        env:
          VERCEL_ORG_ID: team_VWxkrFEiDFEjoLWyxR5odBSJ
          VERCEL_PROJECT_ID: prj_2AN7Gwsp8KegTyg3UVGyiyDJ0fty
